# Dependencies
markdown:            kramdown

redcarpet:
  extensions: ["tables", "fenced_code_block"]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

exclude:      ["*.Rmd"]


# Setup
title:               Analiza Danych w czasie rzeczywistym
tagline:             'kurs dla studentów SGH'
description:         'Real-Time Analytics'
url:                 https://sebkaz.github.io/RealTime
baseurl:             "/RealTime"             
paginate:            5

# About/contact
author:
  name:              Sebastian Zając
  url:               https://sebastianzajac.pl
  email:             sebastian.zajac@sgh.waw.pl

# Custom vars
version:             1.0.0
